200 current  2024-10-20 00:52:09  24.11.20241018.ccc0c21       6.6.57                          *

diff --git a/nixup b/nixup
--- a/nixup
+++ b/nixup
@@ -5,7 +5,7 @@ pushd $scriptDir &>/dev/null
 logfile=nixos-switch.log
 
 # Function to display help message
-display_help() {
+displayHelp() {
 	echo "Usage: $0 [OPTIONS]"
 	echo "Options:"
 	echo "  --verbose             Enable verbose output"
@@ -46,7 +46,7 @@ while [[ $# -gt 0 ]]; do
 			fi
 			;;
 		--help)
-			display_help
+			displayHelp
 			exit 0
 			;;
 		*)
@@ -56,6 +56,7 @@ while [[ $# -gt 0 ]]; do
 	esac
 done
 
+# Formatter
 alejandra $scriptDir
 exitCode=$?
 if [[ $exitCode -ne 0 ]]; then
@@ -65,10 +66,12 @@ if [[ -n "$format" ]]; then
 	exit 0
 fi
 
+# git diff review
 git --no-pager diff -U0
-read -p "Press enter to continue..." ________
+read -p "Press enter to continue..." _
 git add .
 
+# Validate shellrc
 echo "Validating $shellrc..."
 shellrc=$(realpath $scriptDir/modules/home-manager/${shell}rc)
 output=$($shell -c "source $shellrc" 2>&1)
@@ -80,6 +83,7 @@ if [[ $exitCode -ne 0 ]]; then
 	exit $exitCode
 fi
 
+# Update firefox addons
 echo "Updating Firefox addons listing..."
 firefoxAddons=$(realpath $scriptDir/modules/home-manager/firefox-addons.json)
 rm -f $firefoxAddons
@@ -92,29 +96,37 @@ fs.writeFileSync('$firefoxAddons', JSON.stringify(\
 		2\
 	));" | node
 
-echo "NixOS Rebuilding..."
+# Try start garbage collection
+pidFile=nix-collect-garbage.pid
+if [ -f "$pidFile" ]; then
+	if ! ps -p "$(cat "$pidFile")" > /dev/null 2>&1; then
+	if [ $(stat -c %Y "$pidFile") -gt $(date -d '1 hour ago' +%s) ]; then
+			olderThan="30d"
+			sudo nix-collect-garbage --delete-older-than $olderThan &>/dev/null &
+			echo $! > "$pidFile"
+			echo "Started a garbage collection ($olderThan) in the background"
+		fi
+	fi
+fi
 
-line_number=0
-has_errors=
-last_line=""
+# Run nixos-rebuild
+lineNumber=0
+hasErr=
+prevLine=""
+echo "NixOS Rebuilding..."
 sudo nixos-rebuild switch --upgrade --verbose --flake "${scriptDir}#default" 2>&1 | \
 	while IFS= read -r line; do
-		((line_number++))
-		[ -n "$last_line" ] && printf "\033[1A\033[K"
-		last_line="$line"
+		((lineNumber++))
+		[ -n "$prevLine" ] && printf "\033[1A\033[K"
+		prevLine="$line"
 		echo "$line" >> "$logfile"
 		echo "$line"
-		if [[ "$line" == *"warning: error(s) occurred while switching to the new configuration"* ]]; then
-			has_errors=true
+		if [[ "$line" == *"warning: error"* ]]; then
+			hasErr=true
 		fi
 	done
 exitCode=$?
-[ -n "$last_line" ] && printf "\033[1A\033[K"
-
-if [[ -n "$has_errors" ]]; then
-	echo -e "\033[0;33m[log #$line_number]: warning: error(s) occurred while switching to the new configuration\033[0m"
-fi
-
+[ -n "$prevLine" ] && printf "\033[1A\033[K"
 if [[ $exitCode -ne 0 ]]; then
 	echo "\033[0;31mNixOS Rebuild failed with exit code $exitCode\033[0m"
 	if [[ -n "$verbose" ]]; then
@@ -124,7 +136,12 @@ if [[ $exitCode -ne 0 ]]; then
 	fi
 	exit $exitCode
 else
-	echo "NixOS Rebuild completed successfully"
+if [[ -n "$hasErr" ]]; then
+		echo -e "\033[0;33m[log #$lineNumber]: warning: error(s) occurred while switching to the new configuration\033[0m"
+		echo "NixOS Rebuild completed"
+	else
+		echo "NixOS Rebuild completed successfully"
+	fi
 fi
 
 git commit -m "$(nixos-rebuild list-generations | grep current)"
