263 current  2025-01-17 09:17:04  24.11.20241026.86e78d3  6.6.58                          *

diff --git a/nixup b/nixup
--- a/nixup
+++ b/nixup
@@ -13,9 +13,13 @@ abspathrel() {
 # $2: description
 # $3: command to run
 runHourly() {
-	if [ ! -f "$1" ]; then touch "$1"; fi
-	if [ `stat -c %Y "$1"` -lt `date -d "1 hour ago" +%s` ]; then
-		if ! ps -p "`cat "$1"`" &>/dev/null; then
+	if [ ! -f "$1" ]
+	then touch "$1"
+	fi
+	if [ `stat -c %Y "$1"` -lt `date -d "1 hour ago" +%s` ]
+	then
+		if ! ps -p "`cat "$1"`" &>/dev/null
+		then
 			$3 &>/dev/null &
 			echo $! > "$1"
 			echo "Started $2 in the background"
@@ -52,14 +56,19 @@ shell="zsh"
 bcwt=
 
 # Parse command line arguments
-while [[ $# -gt 0 ]]; do
+while [[ $# -gt 0 ]]
+do
 	case $1 in
 		--verbose) verbose="--verbose"; shift ;;
 		--format) format="--format"; shift ;;
 		--sync) sync="--sync"; shift ;;
 		--shell)
-			if [[ -n $2 ]]; then shell=$2 ; shift 2
-			else exit `excho "Error: --shell requires an argument"`; fi
+			if [[ -n $2 ]]
+			then
+				shell=$2
+				shift 2
+			else exit `excho "Error: --shell requires an argument"`
+			fi
 			;;
 		--help) displayHelp; exit 0 ;;
 		--bcwt) bcwt="--bcwt"; shift ;;
@@ -70,8 +79,12 @@ done
 # Formatter
 alejandra $scriptDir
 exitCode=$?
-if [[ $exitCode -ne 0 ]]; then exit $exitCode; fi
-if [[ -n "$format" ]]; then exit 0; fi
+if [[ $exitCode -ne 0 ]]
+then exit $exitCode
+fi
+if [[ -n "$format" ]]
+then exit 0
+fi
 
 # git diff review
 git --no-pager diff -U0
@@ -84,7 +97,8 @@ runHourly "nid-collect-garbage.pid" "Nix garbage collection ($olderThan)" "sudo 
 
 # Run nixos-rebuild
 # Ignore clean working tree
-if [[ -z "$bcwt" ]] && [[ -z `git status --porcelain` ]]; then
+if [[ -z "$bcwt" ]] && [[ -z `git status --porcelain` ]]
+then
 	echo "Working tree is clean - nothing to build!"
 	echo "Use --bcwt to build anyway"
 else
@@ -93,29 +107,22 @@ else
 	hasErr=
 	prevLine=""
 	echo "NixOS Rebuilding..."
-	rm -f $logfile
-	sudo nixos-rebuild switch --upgrade --verbose --flake "${scriptDir}#default" 2>&1 \
-		| while IFS= read -r line; do
-			((lineNumber++))
-			if [[ -z "$verbose" ]]; then if [ -n "$prevLine" ]; then printf "\033[1A\033[K"; fi fi
-			prevLine="$line"
-			echo "$line" >> "$logfile"
-			echo "$line"
-			if [[ "$line" == *"warning: error"* ]] || [[ "$line" == *"error:"* ]]; then hasErr=true; fi
-		done
-	if [[ $? -ne 0 ]]; then
-		if [[ -n "$verbose" ]]; then cat $logfile >&2
-		else cat $logfile | grep --color "error" >&2; fi
-		exit `excho "\033[0;31mNixOS Rebuild failed\033[0m"`
+	sudo nixos-rebuild switch --upgrade --verbose --flake "${scriptDir}#default"
+	if [[ $? -ne 0 ]]
+	then exit `excho "\033[0;31mNixOS Rebuild failed\033[0m"`
 	fi
-	if [[ -n "$hasErr" ]]; then echo -e "\033[0;33m[log #$lineNumber]: non-fatal error(s)\033[0m" >&2; fi
+	if [[ -n "$hasErr" ]]
+	then echo -e "\033[0;33m[log #$lineNumber]: non-fatal error(s)\033[0m" >&2
+	fi
 	echo "NixOS Rebuild completed successfully"
 fi
 
 # Commit changes
 git commit -m "`nixos-rebuild list-generations | grep current`"
-if [[ "$sync" == "--sync" ]]; then git push
-else echo "To push the changes, run '$0 --sync'"; fi
+if [[ "$sync" == "--sync" ]]
+then git push
+else echo "To push the changes, run '$0 --sync'"
+fi
 
 popd &>/dev/null
 # Restart shell
